### ISSUE TITLE
Adding new params

### ISSUE THREAD

**Issue by adriacabeza** [thomasantony/llamacpp-python#5]
Hey Thomas! Awesome work on the wrapper.
I was wondering if there is any plan to continuing expanding new options like the flags complexity or embedding.

Would that be as easy as adding new params to ```llama_init_from_params```?

I am especially interested to see if this is the way to go as the original repo highly changed with the new C-style API.

**Comment by thomasantony** [comment]
I am currently working on porting the bindings to the new API - including any new params that were added. My plan is to keep the bindings very light so that any further application-centric logic can be built on top of it in Python while all the actual inference etc happens in the C/C++ code. 

I will try to keep the performance at par with the original code by making it so that numpy arrays can be directly passed in to the C++ code (e.g. with the "eval()" function) and used without any additional memory-copy operations. 

Not sure if that answers your question.

**Comment by thomasantony** [comment]
@adriacabeza I have merged in the changes. The low-level API exists, but is untested. Tread carefully. :)
